### ISSUE TITLE
crypto_stream_aes128ctr_*() is going away

### ISSUE THREAD

**Issue by jedisct1** [carblue/sodium#2]
Hi Carblue!

And thanks a lot for these bindings!

Just wanted to give you a heads up regarding the `crypto_stream_aes128ctr*` function set.

These functions have been deprecated for a long time, and have been removed in the current dev tree. Libsodium 1.0.15 will not have them.

So, maybe this is something you should remove from your bindings as well in order to avoid linking errors when the new libsodium version will be out.

Cheers,
-Frank.

**Comment by carblue** [comment]
Hi Frank,

the binding is updated to C header version 1.0.15 now.
Thanks for Your info.

Cheers,
Carsten
